homepage:
    path:   /
    defaults:  { _controller: Level7PdnsBundle:Page:homepage }


domain:
    type:     rest
    defaults: {_format: json}
    resource: Level7\PdnsBundle\Controller\DomainController
