Level7\PdnsBundle\Entity\Cryptokeys:
    type: entity
    table: cryptokeys
    indexes:
        domainidindex:
            columns:
                - domain_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        domainId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: domain_id
        flags:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        active:
            type: boolean
            nullable: true
            comment: ''
        content:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
