Level7\PdnsBundle\Entity\Records:
    type: entity
    table: records
    indexes:
        nametype_index:
            columns:
                - name
                - type
        domain_id:
            columns:
                - domain_id
        recordorder:
            columns:
                - domain_id
                - ordername
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        domainId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: domain_id
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        type:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
        content:
            type: string
            nullable: true
            length: 64000
            fixed: false
            comment: ''
        ttl:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        prio:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        changeDate:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: change_date
        disabled:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
        ordername:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        auth:
            type: boolean
            nullable: true
            comment: ''
            default: '1'
    lifecycleCallbacks: {  }
